---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: samba-credentials
  namespace: media
spec:
  encryptedData:
    admin: AgAE8/N/zvL0+e6PTIoIqMq8ineF5EZhLzQsqLrNxM4lRZA8EQ2nQD/h5rV8Wy3H83Kb0xQ1IwQ050JVzJkUXHpL0UlLuQ+sJSlw6GKgXnHXygaQU661ahRnmqJOZmLuU0FlkSVlpS4NRfC6mcKq5E46oSNgqT/3W6L6XT5EMeUfmlQhTDofSO5CaYTPqiqOLRz+svCa8FSXFPdngG6hQ9136YaynV+556hkevk8PhMquS8PLpq2nGWAKYfhSZi6/H0b/RoIC1nDKk0ptYRZK3teMc74NQIFRgDK6pQt3OzRCQDJ87qw94Oej4j0EcrqeYhD4ylBskRSVplmzsWl/XLjeLmGOuP1Vj4D3jbYYQEakrKGjR5A7XIZ6iQC9/2bWOPqSCHz5glSFoOUSIMpbSz16y9cWhxybZ75OetMfANgGKn4HTfPUEpMM+uQLEukQXNVxZAQGYNeXwAzU5B+Ps8NvYdyERaC3eZnvs4dqDfvBL7cPDnASxJZQI5EwYVPG2U7vxbZ/dQCx83H2lU0Ra1r8tXIZ3/hkkHrURN2khYmz+atUFuWTSex7Xo2WI+oLKze7Ht0NqqiTQzhKrlm0Kb9xiFgLKuyFDtzzkam4xHmcjMxCTOe6A12bjL8Rxc2HICk8kDLSinK2N9n8UD2x4Td9H8mQkL4efiHFS1+2dMWT2Kq1ZqJrH3Gg0yW38OIIOZQEcxdC91+FKG0mA==
    default: AgCCblsDvCzuqXWFxvyaMOmsT2QtERKIn4lBB0pILaKjVOVdKVii07qvkQA2tRBxPtzhnhUEHKKnYnxNJssn0BNKfGzb+YxY/iTsDdbetzK4AnnRWPJvvd2tKXbzqKXGiU64Ee8epO+ovlTIjTDcNP5ANkwyheMUrWgONJNkX9sKgUXOVhS4yFNnQKEmSoh7byZZGh3kfCp3Ow+INn+uvDTrIltxC6TO+Qolo9L1yBYnvEVixF0JOEsvmCahXPAPleafwhRsiBgOQJtCBnQWZ5POkMt1ouI7aYDmayV8n59f8EVjq7YWu3H/kS02CKFDEzpQXZCkqC35HnMA+AD7u7pLfxxwK1pi5fwBxGytDfyYgblpY3EjJPqBkbcC5RDdPMhCFVoODMF/xeCXAtevhETF+3wVWUP3sb0Hxl9CmUZftzZWFyZ8LIF6XdWfaVaPMru7UuXVnAbbuyeaENWgQU4bbp4mvdNoyqGekaJXU1+Yaj5jPVPdn6qKTyc6djvdmu/uXruzqqQlDxI8lUbK/CzsRIZMMWBpa+yQpA+YoKgcPdxKAjUEv3iBvTH+PS5bTyp3ZWEwAhFwnTj7w/cDI0lZ7udipzNO8Z4OBeyjjgblNMWNTPkCUNweEs91Cv+B54n4yFL+oP8UMrPuBEl1pelz7lFJaNMJAi0a/N0Cp3NP4aeZ9O58XLWD+BqKH8TyaYBEtj3HRLakzJk=
  template:
    metadata:
      name: samba-credentials
      namespace: media
    type: Opaque
