apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-release
  namespace: cnpg-system
spec:
  chart:
    spec:
      chart: cloudnative-pg
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cnpg-repo
      version: 0.27.0
  interval: 1m0s
  values:
    crds:
      create: true
    config:
      clusterWide: true
      create: true
      maxConcurrentReconciles: 10
    monitoring:
      podMonitorEnabled: true
      podMonitorAdditionalLabels:
        release: monitoring-release
      grafanaDashboard:
        create: true
    resources:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 200Mi
