---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homecloud-postgres-user
  namespace: cnpg-system
spec:
  encryptedData:
    password: AgA37EZCSVNqsBquA+I4qwIUxhLZuA5X0i8QMpq1SC0f7ADb1goJkrdLjIPYkLWYRX4zO5Or+O/Ji2V3hvqkgNhvkAh0ioVFGQlZ53Flp26qRxC878BQ/DGK2EQwAqVLL3irvcOAx/JI/iqD9uoY3TUkd2V9fczUplu39TXriUTh+4xEVJx3+WbBKuIucC6ovh5bE0U0Mkrl10Z8dv9GMPni4JA4XsKiTEs6GUszHRWR+rxy9Gqo1OqRNre5ju5spJdREp/SqcKoch/D9DzKhPqNVH0QitLnOarihVUAGRNL9CyweV4AUCH7zWbiFLNTXFk43HTbSyMU10LV8JfKjLb6oRHq3jE8pPNWyXwpqjijP3N+5ZP50JNaltsuhN21eVkw/B53Qc83aksni2Guru/SVdPHzKTNzb29PynKA7fBpRfZxyaAqCQJXVuvHrzFIuq2N4+b+wRgAgQe93RGYKK+r3kdG/7aY5teaYVWvquxHy8IsNlj4KrQCR1H2z4n9Em3+SpgyImGKj4XmCJ/nLlLxTTagfIbJ1fkQ+VqXUIJDu8YXyl3Z0wIHyH4G8oQWabAyf0dN5CJnVE+6e4tfILhAc1nAiAjulc7Ea9xgDYKUSbHdEirCrHnFSTOWBvzpUMRQNfgI1YwtyV41uojXOZ+NMLRmLbimy2XNRcwbFV9v4X1GHz6T64B4A5iM2l4Fb+TV86SStDh8eFunJDMKMY=
    username: AgApWG2CDI+2mYNe+57xxCi4jqWuBCuwrJhghYFl9ZDr/iHSYPHNeC6ypNYDm7HbEffv607o+ii3QqtG9KqtCkuhyqWMnIM93UkDzwHSXNfg3h4srTBcMuYP840/8Yu9GY6WtCbhGRxALnLeK0o3THAZAUkhscRQFRpniSCb0uMgwdoLr87KyIsXhup5MnLerfh1Zk0gyKq15WQSHcCnL+AtaGmt9eKFsjKGE9yJDSRUjE+uooAsq+7PisHukQODnlWllocsO0zs3ua2o5aREMizqx3JG6V2u6AFjzFQ2xtILQkzU6ZOOBKcxyNTa7FhQPTOqy3qnyDAriJlRCL8rpFKwjlpWZPOpGxGw4rkJyiC1Jd/yVFi8JaamuUKZtdrpTzntcZoVNpNv74hW8zaaVWXs7dsOubEc3QTfKcETeG9AMWRnLlRk5T4CZ6nSyqcpyBbBMH15wnmAUR2BBX+7qlx8pYSEmh3p0OCUX8KYqv6ij2fltpjY/jwPRdJIxhRWkPSiDSOdTuhVA8Z7EZ7HQeqLPoA0UH3fVkpZs4Yx3lT2aeBAGqIuZT5Aj2gzoPF5jsG1as3IqfKckEDQWSsUkMJL/HPoq5nlb80Jb+WZbFtCABTgtdVMSCJ5uYITyR0XYYZOQYGSfUzG4csYyKzg0J1+I1NY+ggc5szIvkr5zL5V2nvngIIevUVmkQBMdYj3CpCoN7xbC0y
  template:
    metadata:
      name: homecloud-postgres-user
      namespace: cnpg-system
    type: kubernetes.io/basic-auth
