apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: github-arc-runner-nixconf
  namespace: github-arc-runner
spec:
  chart:
    spec:
      chart: gha-runner-scale-set
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: github-arc-runner-repo
  interval: 1m0s
  values:
    githubConfigUrl: "https://github.com/Loeffeldude/nixconf"
    githubConfigSecret: github-token
    maxRunners: 3
    containerMode:
      type: "dind"
