apiVersion: v1
kind: Service
metadata:
  name: vpn-proxy
  namespace: media
spec:
  selector:
    app: vpn-proxy
  ports:
    - name: privoxy
      port: 8118
      targetPort: 8118
    - name: socks
      port: 9118
      targetPort: 9118
