apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repositories.yaml
  - releases/secrets
  - releases/cloudnative-pg
  - releases/longhorn
  - releases/monitoring
  # - releases/mcp-context-forge
  # - releases/nextcloud
  - releases/velero
  # - releases/penpot
  # - releases/jenkins
  - releases/github-arc
  - releases/kubetail
  # - releases/vault
