---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github_token
  namespace: github-arc-system
spec:
  encryptedData:
    github_token: AgB7+13V+d9pvu1RYmHGQtfGhUoqAMWBlPM7X5xCaPOjUfvatBuorHev1F6mdhgmA8n/xkZImoPe+YJtOA29xnh/X8qra5fz/v6Al4mwdusg+j7z9yRRIT4YRbCFmGOUTkK3N4NP/bdt7drpHP2vjWXdkkEHebVvS6BXlYkFEu3MeTPueRr85pffDBoqZV0X9M+xHwXG7LsGhPWtoTAOmHoqYc3DPgfDS78OJiltMRiMdtGmUOvPNHE1avIoJM3DEHO/Fx4iQ57MZPolp5zuB0FPfsHD39AoR+qriL2RfIp4gi8I9pu98jm6CvB9y1g5KwdVVoaEWt6JEI4M5HxxzcStRC7r/XWr09FVxVOx+gtqmh+WOW7sIGY9MtK3zuFWdN4yydIHFxev2d2eg4cYXn/1SiXm+te4mo74Y1nzu6V8Fd15GlHHfnxjDEa7znN7zA3bTcEodb9GGUT/r5IdWnx/BAgCGy+RvjvHjfNYO4dJ+Vfx3rme5KRar4sgRx0HEaN1RPdZTjuiia8guAD2oaW/NsmpR0Qgp719Xn5d8hPcVuw0TXJ/eaM0Df4z1oG93r7AsdEBgoYimZpck87TtsVcjHMJlbRyHVDc7MIoibzZCN5dlRUu1L5+huvQScXlGps0wWgjU50x2soG7W5Q7/B84OOt87LKg2DCtbDXdYhwGeUH9Xjww8hYoGV1Vw4xTv/wXz2lzMPJ3qiXQHC7JTl3qgSWcI77KQ7CjOrshf3S32TR4/cMPaW9
  template:
    metadata:
      name: github_token
      namespace: github-arc-system
    type: Opaque
