---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: github-arc-runner
spec:
  encryptedData:
    github_token: AgAivAlaY5F4xDm7v8u0FsTzwfp0PchhVDDe9y1AOnrtmM7NjF7jlfPnn+HrBYeto3rpAdgRK+pZ649/Cv30oVqivML+bN0JC9BxyWLi91k6dZC1uJRUVg5jf/jXmbSWdSJqsiEDfenlLzgiN8FGK6KTBhrnJTliqpIZ4lYC6nc/Im5f9PEDW/TYONYnwSr0DroUehXmGakcifDODudHhbXojif/2ubj8fPejuvWvu3S9H5tSZJmVWKQgkzZnXDf4J6LdZA3/I0ZwP5PU9HZ2HAvEnHV5wxzBz2xEnmaXdtDGv3FXlz8j6XUy7n7xEjWkC+YXO9a/xOhFeJ756KdSYAj8OmvhmC2YrRa+c7gqthAQUkQsfcz2O5xyYqqVve3LWu7oVzCkykmmljMBdHIc1Gcv5+mIfCCbar6ea/nPCeOHbP0czRUtWyOOTQndzTWnkeon8/EXz85apSEJWVKuHyhCj/6UuaZxn5FnJKbmpMCszJfI1un9R/toHkvfT2CDgAcOO/i/VY6fSg+6BSRZejIGlBQ1qko1sPFNieNOH8KgPLSP03VafY8YkTlqKfVwP3DbQE6HgIz/X3uRTGY6ZDgj1FtusGIZfRK3UG8XWbxR8JwV7kOfXrQe+ls6s/bVgYu7FoBXvP10Gs7VSTEwQ620a9lo7IT4Wh7NISzFaHRmqGwwIK2+yyBNq5RLv5DHpnFTmKURdv15Mmj9XYGazh2BiffuwDFUpNbBbI5qJwBX554jzyLcbDRJx9vJ2f5NfSANZ2yp2fEUUygnjON0u5UtliUJK6J+6fX6Xh0q7yDivFWTR7Uz5JvOtzL2LY=
  template:
    metadata:
      name: github-token
      namespace: github-arc-runner
    type: Opaque
