---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: github-arc-runner
spec:
  encryptedData:
    github_token: AgC2bwx/B4MFGdZQROILLTbS592k/SBpp8P/7TDNMxREjhv6kCHLXtRTBffKYD6qvOC8CIiaEZg++0ROZUIg1MFlnhLo550P+rTmjAkWiOqGnC2QcyshjUQIoj/0wGyfxRQ0K7jDpoKw+LxmMBPAeCGE3hpbdOpDkGdnRO3uGz7JW4ByVF55JZK4J/SO/Gpb7dTxYKtn9ob17gAgzkd6ulruXzmmfw/KkH8bggZ4lwPfVG2HFrr1ksVqTGBImGD+V9w3vagkB5vLm9Pz60eDGPXl5OR7/WUoK4rtAcmQTAKzgh9UufFPRntg0j2tNGc1UcsMYRvF6zU1NlA+h7kg6JMD3W+yQ2wmua5ysb9Ih3dD25UowXtjFn8sTmM3lZgfh3fyVqzc2GWpupfv2TlFsGPpcTeFxJ7LAYyagjQaE99oTcQDBbg0gB1tYZFwTb8hKjy8QyR/6LOx1nB91Qs5xwf59n5NzHY0ru5y9o7CmC8CYsL7LUZtAVbUCf5f8O+JHtJUDgXoMLC98K/VNcwlw+tQfo/8uLHlt6Z3YL9ixBklD+yDrl57KHjBo9yiK7MFmhKcDUaLq3tLXU9mMEDB1WybNvkh5chqkEzQA6j6hUc1gcKztCQW95XZEqjbKEsaIp9ZqT0UMexlwXaFrvy9Yq4ZH4XqiU/2nWrPbVVkcFTeRo3Rizlqt8/sdUCjago9o1zkMQG2qI3XWFkQikoVBRikuu6n2AvGoGFeEhUYxsrUKPD7DZCgTlLQ
  template:
    metadata:
      name: github-token
      namespace: github-arc-runner
    type: Opaque
