---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: github-arc-system
spec:
  encryptedData:
    github_token: AgAAb3OHKYGy1hN22ffvFDwduwGAayyuqCAVLMF2EiKRpJGcOngjVObzRAk5lFDZOX/d7FJhkc+iLrqO064urdvbOPKWt3uqVKnEVWU7X69oS8RjcJWQAbWZ1yQZt48cFGaNAqrQyNRqzTr2Najj4kfoLptq1/Kf5W4KOeawtVWPaHH8vfu3ZcE/9LsRpL3XBVJ6SfjkW82DOmVnH0mt44V52fTUEF22aVjTrekOUrJ+4+dcOCGEI7p0kW6VOU5bvA1ZQOEmi57mD92InFl7JriA65yq9bkklr+5hu53eqFsp/BJb9BJqemDyDBnlFx/HA3QtYOR7q8dwJJoeh18bD7Bl2/vE/eAFmxNGgU8mS9o3lFkz/QcJEhVwcp5a/EIfG9HqrDNAsMsWJPFnZkty0sxBb5A7HkqO5o6s8nyiFCN79DeCGU/XlEdb2z1xpRe7JcZB0vMkhWxdBA2RRFySD9YH83tdYwV9YFdeZdg/bMv5ZXXfYSUCAjhz4yom2+ASA6E617eGyac+Jtx7R8mlbreeBRIYA0DV5g3FOkWTOdCk27ot0GzyYh6mZASPRmQMwZL/ox5XYPLqsxju8P8gnSZ+01RJ4qZ5tHrlGpiAN34icGl46fmaRvgsj8MhANeBHKE8D6/mRcv2mR8sq9VCiyqUOz6YvEoVCYEXMVaq5lQb3wP5D39QO20nsNt9IeIDOarOcuHdQT+z68FcoKY7yWOXCmoihhvYSq2OC74qQexRjrVOoOsOqC0
  template:
    metadata:
      name: github-token
      namespace: github-arc-system
    type: Opaque
