---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github_token
  namespace: github-arc-system
spec:
  encryptedData:
    github-token: AgCpC36mcqJPxqeTR3F6eTcOpu9uabfRqKyop0KdczDmJRe196aXNqkMvzKskPbtKgs4TjFZOGQQzme/eH6Xphnoz4LJAdzWCqmjULqDyk/i832YunHRiF43RSUk7q/eNnMQyP+Vd2/Ir4Ro2/x0xwuNNIjqEBRN30W55vWvNfxFTBZagRE5Sz7SArWc335sa9ZT0v7xYsLM3Qqco+eGnDrdjbxE9L9pNB4uC3P8J5RzDEOAh5/bWPNgBrvkqAb+V7emmEAGNoYrPMpOG+ZQpdjidwgWIk/e52YQn98xmGLscHAoofpz54iseLJhRiqIYaV4pFOL9z3g1sChpfQ/Qk/UMS5eaJ2p6rj+bqltfODaelV/wRrnwe6faXiVWvDpB/VuliXYpBqO8qfCFk/C32GC07GyEmPBH0RqVoyzJJ0Mexfwfci4QJK9fFRZd7Ypoj1oA0ZHUXUFjyl3xtkn4uNAvEpSFaWoLkIuuYb6uSM85+OoFlRi2SceLoSN3uwCTux80bJzHXTS6o+aIdA2YfG9IUG6NleyT+aq1CRRvBtIWBT4dbK4un0GI7LRLoGyUnpygK3NXqM6dv9iTrAe1nc/78QICg85rytoyUiJjs5ixuQBtJpMhM2giTLkZDJ3IbhDbBDjsCUAL4gIcid7K8wdh8e0wLTuyb5h09RL2WnLUBbKrb2XiIE/PPw8kyw2Xwhg7N3LQcrPUIZtVTcX5sIB/q/f6fZMSg1kL1lELKPM2pVSd50f1NyN
  template:
    metadata:
      name: github_token
      namespace: github-arc-system
    type: Opaque
