apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolver
  namespace: media
spec:
  selector:
    matchLabels:
      app: flaresolver
  template:
    metadata:
      labels:
        app: flaresolver
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - homeserver-2
      containers:
        - name: flaresolver
          image: ghcr.io/flaresolverr/flaresolverr:latest
          ports:
            - containerPort: 8191
              name: proxy
            - containerPort: 8192
              name: prometheus
          env:
            - name: CAPTCHA_SOLVER
              value: none
            - name: PROMETHEUS_ENABLED
              value: "true"
            - name: TZ
              value: Europe/Berlin
            - name: PROXY_URL
              value: "socks5://qbittorrent:9118"
            - name: PROXY_USERNAME
              value: "admin"
            - name: PROXY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qbittorrent
                  key: socks-pass
      restartPolicy: Always
